Going to the latest Tag

diff --git a/resources/dokuwiki-docker/bin/dokuwiki-docker-entrypoint b/resources/dokuwiki-docker/bin/dokuwiki-docker-entrypoint
--- a/resources/dokuwiki-docker/bin/dokuwiki-docker-entrypoint
+++ b/resources/dokuwiki-docker/bin/dokuwiki-docker-entrypoint
@@ -1,8 +1,12 @@
 #!/bin/bash
 
 if [[ "${DOKU_DOCKER_ENV}" != "dev" ]]; then
-  # Exit if any error
-  set -e
+  # flag
+  # e - Exit if any error
+  # u - Treat unset variables as an error when substituting
+  # o pipefail - the return value of a pipeline is the status of the last command to exit with a non-zero status or zero if no command exited with a non-zero status
+  # E - the ERR trap is inherited by shell functions
+  set -Eeuo pipefail
 fi;
 
 # Functions
